spring.application.name=pi-projsoft

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:provadb}
spring.datasource.username=${DB_USER:curso}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8080}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always